language: java
install: true

jdk:
- oraclejdk8

script:
- ls
- pwd
- cd common && \
  ./gradlew --warning-mode=all compileJava && \
  ./gradlew --warning-mode=all test itest slowtest && \
  cd ..

- cd theseus && \
  ./gradlew --warning-mode=all compileJava && \
  ./gradlew --warning-mode=all test itest slowtest && \
  cd ..