language: java
install: true

jdk:
- oraclejdk8

script:
- pwd
- cd common && \
  ./gradlew --warning-mode=all buildJava && \
  ./gradlew --warning-mode=all test itest slowtest
- cd theseus && \
  ./gradlew --warning-mode=all buildJava && \
  ./gradlew --warning-mode=all test itest slowtest